<a href="https://colab.research.google.com/github/pferroni/aula_senai/blob/main/aula120225.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
[1] #Libraries
  import numpy as np


IndentationError: unexpected indent (<ipython-input-12-91bb851c989a>, line 2)

In [ ]:
w1,w2,w3 = 0.3, 0.2, 0.5
print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_unid = 65

In [ ]:
# um gestor de TI precisa verificar se um numero de serie de um computador é valido. Se o numero de serie for maior de 1000 e menor de 9999, ele é considerado valido. Caso contrario, o sistema deve mostrar uma mensagem de erro.

In [ ]:
numero_serie = int(input ('digite o numero de serie:'))
if 1000<= numero_serie <=9999:
  print('numero ok')
else:
  print('numero Nok')



digite o numero de serie:1001
numero ok


In [ ]:
# dados Climaticos da região A
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_unid = 65

#aplicando o modelo
regiaoA_goiaba = (regiaoA_temp * w1) + (regiaoA_chuva * w2) + (regiaoA_unid * w3)

print(f'Na regiao da produção de {regiaoA_goiaba} tonelafdas por hectare')


Na regiao da produção de 52.5 tonelafdas por hectare


In [ ]:
w1,w2,w3 = 0.3, 0.2, 0.5
print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
# dados Climaticos da região A
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_unid = 65

#aplicando o modelo
regiaoA_goiaba = (regiaoA_temp * w1) + (regiaoA_chuva * w2) + (regiaoA_unid * w3)
print(f'Na regiao da produção de {regiaoA_goiaba} tonelafdas por hectare')


Na regiao da produção de 52.5 tonelafdas por hectare


In [ ]:
regiaoA = [22,67,65]
regiaoB = [24,88,95]
regiaoC = [17,134,50]
regiaoD = [18,96,70]

In [ ]:
pesos = [w1,w2,w3]

In [ ]:
a=5
b=10
def teste(a,b):
  print(a+b)

In [ ]:
def produçao_goiaba(regiao,pesos):
  result = 0
  for x, w in zip(regiao, pesos):
    result += x*w
  return result

In [ ]:
# produção da regiao A,B,C,D
print(produçao_goiaba(regiaoA, pesos))
print(produçao_goiaba(regiaoB, pesos))
print(produçao_goiaba(regiaoC, pesos))
print(produçao_goiaba(regiaoD, pesos))

52.5
72.3
56.9
59.6


In [ ]:
teste(a,b)

15


In [ ]:
#importado o numpy

import numpy as np

regiaoA = np.array([22, 67, 65])
print (type(regiaoA))
pesos = np.array ([w1, w2, w3])
print(type(pesos))



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(regiaoA, pesos)
print('regiao A:{}'.format(reg_a))

regiao A:52.5


In [ ]:
reg_a = np.dot(regiaoB, pesos)
print('regiao B:{}'.format(reg_a))

regiao B:72.3


In [ ]:
#Exemplos
#Lista em Python

arr1 = list(range(2000000))
arr2 = list(range(1000000,3000000))

# vetor em Numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [ ]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1 * x2
print(result)

4666663666667000000
CPU times: user 373 ms, sys: 0 ns, total: 373 ms
Wall time: 373 ms


In [ ]:
%%time
print(np.dot(arr1_np, arr2_np))

4666663666667000000
CPU times: user 5.28 ms, sys: 0 ns, total: 5.28 ms
Wall time: 4.08 ms


In [ ]:
dados_climaticos =np.array([[22,67,65],
                          [24,88,95],
                            [17,134,50],
                            [18,96,70]])
print(dados_climaticos)

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
print(dados_climaticos.shape)
print(pesos.shape)
print(pesos.dtype)
print('________')
print(dados_climaticos.dtype)
float64
-------------
int64

SyntaxError: invalid syntax (<ipython-input-113-4cd2c64cf333>, line 7)

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
# codigo zip combinando listas

nomes = ['Alice','Bob','Charlie']
idades = [25,30,35]

#combinando listas usando zip
lista_combinada = list(zip(nomes,idades))
print(lista_combinada)
#Saida [('Alice'25), ('Bob',30), ('Charlie',35)]

[('Alice', 25), ('Bob', 30), ('Charlie', 35)]


In [2]:
np.matmul(dados_climaticos, pesos)
array([52.5, 72.3, 56.9, 59.6])

NameError: name 'np' is not defined

In [13]:
#aula 1202

import numpy as np

In [19]:
Goiaba = np.genfromtxt('/content/Goiaba.csv', delimiter=',')

Goiaba


array([[23., 29., 95.],
       [24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [20]:
pesos = np.array ([0.4,0.2,0.9])
rendimento = Goiaba @ pesos

In [31]:
# incluir o resultado na regiao do array

resultado = np.concatenate((Goiaba, rendimento.reshape(4,1)), axis=1)



In [32]:
resultado

array([[ 23. ,  29. ,  95. , 100.5],
       [ 24. ,  20. ,  21. ,  32.5],
       [ 18. ,  23. ,  16. ,  26.2],
       [ 19. ,  30. ,  36. ,  46. ]])

In [36]:
# agora é so salvar
np.savetxt('goiaba_result.csv',
           resultado,
           fmt='%.2f',
           delimiter=',',
           header= 'temperatura,precipitação,umidade,rendimento',comments='')

In [ ]:
#importação de dados do excel, utlização de tabelas e execução de formulas)